# server:
#   addr: http://localhost:8080

# generation:
#   modelcode: gemini-3-flash-preview
#   titlemodelcode: gemini-2.5-flash-lite
#   temperature: 0.0
#   topp: 0.95
#   topk: 0
#   outputlength: 65536
#   streamdelay: 0

# clipboard:
#   copycmd: ""
#   pastecmd: ""

# context:
#   dirs:
#     - .
#   files:
#   exclusions:

# ui:
#   markdowntheme: dark
